@Presentation_HostAddress = http://localhost:5062

GET {{Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Presentation_HostAddress}}/api/component/
Accept: application/json

###

GET {{Presentation_HostAddress}}/api/component/1
Accept: application/json

###

POST {{Presentation_HostAddress}}/api/component/
content-type: application/json
"Board1"

###

POST {{Presentation_HostAddress}}/api/Account/SignIn
Content-Type: application/json
{
    "Email": "admin@auth.com",
    "Password": "PASSw0rd!"
}

###

POST {{Presentation_HostAddress}}/api/Account/SignUp
Content-Type: application/json
{
  "FirstName": "Muhammad",
  "LastName": "Najafi",
  "Email": "mjn220@gmail.com",
  "Password": "Password123!"
}

###

POST {{Presentation_HostAddress}}/api/Account/GetAuthenticationState
Content-Type: application/json
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQxY2E4YzkzLTgyMjUtNDJmNS1iNGRmLTQwYjBjYWNhMDU1ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGF1dGguY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFkbWluQGF1dGguY29tIiwiRmlyc3ROYW1lIjoiTXVoYW1tYWQiLCJMYXN0TmFtZSI6Ik5hamFmaSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzgxMTA0NzE2LCJpc3MiOiJCaWxib2FyZEFQSSIsImF1ZCI6IkJpbGJvYXJkQ2xpZW50In0.c7OhuJHoWNDLxaOIcB_DJCgg5NqKot-CyEAjHmw1JGk"