@Presentation_HostAddress = http://localhost:5062

GET {{Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Presentation_HostAddress}}/api/component/
Accept: application/json

###

GET {{Presentation_HostAddress}}/api/component/1
Accept: application/json

###

POST {{Presentation_HostAddress}}/api/component/
content-type: application/json
"Board1"

###

POST {{Presentation_HostAddress}}/api/Account/SignIn
Content-Type: application/json
{
    "Email": "admin@auth.com",
    "Password": "PASSw0rd!"
}

###

POST {{Presentation_HostAddress}}/api/Account/SignUp
Content-Type: application/json
{
  "FirstName": "Muhammad",
  "LastName": "Najafi",
  "Email": "mjn220@gmail.com",
  "Password": "Password123!"
}