  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68601CB65CF643ABBABB546DE38E0C64 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_99861BAFA9CD48ACA9802C708BD4340F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1EE2B27BF2704B3A9487D4C2FF0CD460 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Bilboard'
          slot-name: 'Production'
          package: .

      - name: Deploy to Hetzner VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "./"
          target: ${{ secrets.HETZNER_APP_PATH }}

      - name: Restart Hetzner service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            systemctl daemon-reload
            systemctl restart bilboard.service
            systemctl status bilboard.service --no-pager
